sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 13241324a
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5t9bK7zjeNRrTHv5nEK8
    access-key-secret: nvG3RZT5nJMWQVSwBQIZFAHwwNubdI
    bucket-name: web-lisen-test
  redis:
    host: 192.168.72.128
    port: 6379
    password: 13241324aA
    database: 0
